[package]
name = "rust-graphics-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
glutin = "0.29.1"
tobj = "4.0.3"
glam = "0.30.9"
image = "0.25"
anyhow = "1.0"

[lib]
name = "rust_graphics_engine"
path = "src/lib.rs"
